language: python
python:
#  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
# command to install apt dependencies 
before_install:
  # Install RethinkDB
  - sudo add-apt-repository -y ppa:rethinkdb/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes rethinkdb
  # Install ssdeep
  - sudo apt-get install libfuzzy2
  - sudo apt-get install libfuzzy-dev
  - sudo apt-get install ssdeep
  # Install GeoIP
  - sudo apt-get install libgeoip-dev
  - sudo apt-get install libxml2-dev
  - sudo apt-get install libxslt1-dev
  # Install LDAP
  - sudo apt-get install libldap2-dev
  - sudo apt-get install libsasl2-dev
  - sudo apt-get install libssl-dev
# command to install pip dependencies
install: 
  - pip install -q -r requirements.txt
  - pip install coveralls
# command to set environment variables
before_script:
  - export CSRF_SESSION_KEY=test_secret
  - export SECRET_KEY=test_secret
  - export MAIL_SERVER=smtp.example.com
  - export MAIL_PORT=465
  - export MAIL_USERNAME=username
  - export MAIL_PASSWORD=password
  - export MAIL_SENDER=support@malice.com
  - export MAIL_ERROR_RECIPIENT=support@malice.com
  - export LDAP_HOST=ldap.example.com
  - export LDAP_DOMAIN=example.com
  - export LDAP_AUTH_TEMPLATE=login.html
  - export LDAP_PROFILE_KEY=employeeID
  - export LDAP_AUTH_VIEW=login
  - export CAPTCHA_PUBKEY=pubkey
  - export CAPTCHA_PRIVKEY=privkey
  - sudo rethinkdb &
#  - python manage.py createdb
#services:
#  - sqlite3
#  - mongodb
# command to run tests
script:
#  - nosetests -v --with-coverage --cover-package=app --cover-branches --cover-erase --cover-html --cover-html-dir=cover
  - coverage run --source=app manage.py test
after_success:
  coveralls
